name: config test
description: plugin to test plugin config format
author: https://github.com/chrisdothtml
configuration:
  properties:
    vars:
      type: array
      items:
        type: string
  additionalProperties: false
